# Generated by Django 2.1 on 2018-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('vendor_ext', models.CharField(max_length=3)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_email', models.EmailField(max_length=254)),
                ('item', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('shipping_address', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('extension', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
